// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlUZ5VMkIIBJFxLS_ALD-oJfYh5MjtX1o',
    appId: '1:778652530713:web:7755992493055020051288',
    messagingSenderId: '778652530713',
    projectId: 'myjainshasan-240a2',
    authDomain: 'myjainshasan-240a2.firebaseapp.com',
    databaseURL: 'https://myjainshasan-240a2.firebaseio.com',
    storageBucket: 'myjainshasan-240a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUUF7qtn-_6mhDW0Ybm6bMIhafENO7FHY',
    appId: '1:778652530713:android:0ac76e042974173a051288',
    messagingSenderId: '778652530713',
    projectId: 'myjainshasan-240a2',
    databaseURL: 'https://myjainshasan-240a2.firebaseio.com',
    storageBucket: 'myjainshasan-240a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS9RFlvOWm7RkKdklTcZBvmvt50_N24yM',
    appId: '1:778652530713:ios:32b57689b7ecbc12051288',
    messagingSenderId: '778652530713',
    projectId: 'myjainshasan-240a2',
    databaseURL: 'https://myjainshasan-240a2.firebaseio.com',
    storageBucket: 'myjainshasan-240a2.firebasestorage.app',
    androidClientId:
        '778652530713-hgljomi7pe5shi761kr5ve6rpuval36e.apps.googleusercontent.com',
    iosBundleId: 'com.axlpl.delivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS9RFlvOWm7RkKdklTcZBvmvt50_N24yM',
    appId: '1:778652530713:ios:32b57689b7ecbc12051288',
    messagingSenderId: '778652530713',
    projectId: 'myjainshasan-240a2',
    databaseURL: 'https://myjainshasan-240a2.firebaseio.com',
    storageBucket: 'myjainshasan-240a2.firebasestorage.app',
    androidClientId:
        '778652530713-hgljomi7pe5shi761kr5ve6rpuval36e.apps.googleusercontent.com',
    iosBundleId: 'com.axlpl.delivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlUZ5VMkIIBJFxLS_ALD-oJfYh5MjtX1o',
    appId: '1:778652530713:web:eb76999064dfc216051288',
    messagingSenderId: '778652530713',
    projectId: 'myjainshasan-240a2',
    authDomain: 'myjainshasan-240a2.firebaseapp.com',
    databaseURL: 'https://myjainshasan-240a2.firebaseio.com',
    storageBucket: 'myjainshasan-240a2.firebasestorage.app',
  );
}
