part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const AUTH = _Paths.AUTH;
  static const SPLASH = _Paths.SPLASH;
  static const BOTTOMBAR = _Paths.BOTTOMBAR;
  static const TRACKING = _Paths.TRACKING;
  static const SHIPNOW = _Paths.SHIPNOW;
  static const HISTORY = _Paths.HISTORY;
  static const PICKUP = _Paths.PICKUP;
  static const POD = _Paths.POD;
  static const PROFILE = _Paths.PROFILE;
  static const CONSIGNMENT = _Paths.CONSIGNMENT;
  static const RUNNING_DELIVERY_DETAILS = _Paths.RUNNING_DELIVERY_DETAILS;
  static const ADD_SHIPMENT = _Paths.ADD_SHIPMENT;
  static const DELIVERY = _Paths.DELIVERY;
  static const NOTIFICATION = _Paths.NOTIFICATION;
  static const MYORDERS = _Paths.MYORDERS;
  static const CUSTOMER_TRACKING_DETAILS = _Paths.CUSTOMER_TRACKING_DETAILS;
  static const SHIPMENT_RECORD = _Paths.SHIPMENT_RECORD;
  // static const REGISTAR = _Paths.REGISTAR;
  static const REGISTER = _Paths.REGISTER;
  static const OUTBOUND_MENU = _Paths.OUTBOUND_MENU;
  static const OUTBOUND_HUB_SCAN = _Paths.OUTBOUND_HUB_SCAN;
  static const OUTBOUND_HUB_SCAN_LIST = _Paths.OUTBOUND_HUB_SCAN_LIST;
  static const OUTBOUND_BAGGING = _Paths.OUTBOUND_BAGGING;
  static const OUTBOUND_BAG_LIST = _Paths.OUTBOUND_BAG_LIST;
  static const OUTBOUND_BAGGING_DETAILS = _Paths.OUTBOUND_BAGGING_DETAILS;
  static const OUTBOUND_BAGGING_REPORT = _Paths.OUTBOUND_BAGGING_REPORT;
  static const OUTBOUND_MANIFEST = _Paths.OUTBOUND_MANIFEST;
  static const OUTBOUND_MANIFEST_LIST = _Paths.OUTBOUND_MANIFEST_LIST;
  static const OUTBOUND_MANIFEST_REPORT = _Paths.OUTBOUND_MANIFEST_REPORT;
  static const OUTBOUND_LINEHAUL = _Paths.OUTBOUND_LINEHAUL;
  static const OUTBOUND_LINEHAUL_LIST = _Paths.OUTBOUND_LINEHAUL_LIST;
  static const OUTBOUND_LINEHAUL_EDIT = _Paths.OUTBOUND_LINEHAUL_EDIT;
  static const OUTBOUND_LINEHAUL_PRE_ALERT = _Paths.OUTBOUND_LINEHAUL_PRE_ALERT;
  static const OUTBOUND_SECTOR_PICKUP = _Paths.OUTBOUND_SECTOR_PICKUP;
  static const OUTBOUND_SECTOR_PICKUP_LIST = _Paths.OUTBOUND_SECTOR_PICKUP_LIST;
  static const OUTBOUND_REMOTE_DETAIL = _Paths.OUTBOUND_REMOTE_DETAIL;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const AUTH = '/auth';
  static const SPLASH = '/splash';
  static const BOTTOMBAR = '/bottombar';
  static const TRACKING = '/tracking';
  static const SHIPNOW = '/shipnow';
  static const HISTORY = '/history';
  static const PICKUP = '/pickup';
  static const POD = '/pod';
  static const PROFILE = '/profile';
  static const CONSIGNMENT = '/consignment';
  static const RUNNING_DELIVERY_DETAILS = '/running-delivery-details';
  static const ADD_SHIPMENT = '/add-shipment';
  static const DELIVERY = '/delivery';
  static const NOTIFICATION = '/notification';
  static const MYORDERS = '/myorders';
  static const CUSTOMER_TRACKING_DETAILS = '/customer-tracking-details';
  static const SHIPMENT_RECORD = '/shipment-record';
  // static const REGISTAR = '/registar';
  static const REGISTER = '/register';
  static const OUTBOUND_MENU = '/outbound-menu';
  static const OUTBOUND_HUB_SCAN = '/outbound-hub-scan';
  static const OUTBOUND_HUB_SCAN_LIST = '/outbound-hub-scan-list';
  static const OUTBOUND_BAGGING = '/outbound-bagging';
  static const OUTBOUND_BAG_LIST = '/outbound-bag-list';
  static const OUTBOUND_BAGGING_DETAILS = '/outbound-bagging-details';
  static const OUTBOUND_BAGGING_REPORT = '/outbound-bagging-report';
  static const OUTBOUND_MANIFEST = '/outbound-manifest';
  static const OUTBOUND_MANIFEST_LIST = '/outbound-manifest-list';
  static const OUTBOUND_MANIFEST_REPORT = '/outbound-manifest-report';
  static const OUTBOUND_LINEHAUL = '/outbound-linehaul';
  static const OUTBOUND_LINEHAUL_LIST = '/outbound-linehaul-list';
  static const OUTBOUND_LINEHAUL_EDIT = '/outbound-linehaul-edit';
  static const OUTBOUND_LINEHAUL_PRE_ALERT = '/outbound-linehaul-pre-alert';
  static const OUTBOUND_SECTOR_PICKUP = '/outbound-sector-pickup';
  static const OUTBOUND_SECTOR_PICKUP_LIST = '/outbound-sector-pickup-list';
  static const OUTBOUND_REMOTE_DETAIL = '/outbound-remote-detail';
}
