#!/usr/bin/env bash
# Batch 1 — verified Sarvesh QA curls (curl only, no Python).
set -euo pipefail
TOKEN="${OUTBOUND_BEARER_TOKEN:-ecf2c67fd1b93af39f00ddf0ced734ac1cccc7ea4f51725e0b4a4dfff20ca9e7}"
BASE='https://my.axlpl.com/messenger/services_v8/api.php'
OUT='/Users/apple/Desktop/flutter_project/axlpl_delivery/docs/outbound_batch1_verified.md'
HDR=(--header "Authorization: Bearer ${TOKEN}" --header 'X-App-Version: 22.1.0' --header 'X-App-Platform: ios')

run_block() {
  local title="$1"
  local curl_show="$2"
  shift 2
  echo "## ${title}" >>"$OUT"
  echo >>"$OUT"
  echo '**Request curl**' >>"$OUT"
  echo '```bash' >>"$OUT"
  echo "$curl_show" >>"$OUT"
  echo '```' >>"$OUT"
  echo >>"$OUT"
  echo '**Response**' >>"$OUT"
  echo '```json' >>"$OUT"
  local out http body
  out=$("$@" 2>&1) || true
  http=$(echo "$out" | tail -1 | sed 's/__HTTP__://')
  body=$(echo "$out" | sed '$d')
  [[ -z "$body" ]] && body="(empty)"
  echo "$body" >>"$OUT"
  echo '```' >>"$OUT"
  echo >>"$OUT"
  echo "**HTTP:** ${http}" >>"$OUT"
  echo >>"$OUT"
  echo '---' >>"$OUT"
  echo >>"$OUT"
}

cat >"$OUT" <<'HDRDOC'
# Outbound Batch 1 — Verified curls (Sarvesh QA)

Gateway: `https://my.axlpl.com/messenger/services_v8/api.php?request=<action>`

- **No** `platform` query/body (production iOS app).
- POST mutations use **`multipart/form-data`** (`--form`).
- GET list/detail endpoints return **raw JSON array or object** (no `"status":"success"` wrapper).

QA IDs: hub docket `558751776258671`, bagging docket `825411779084407`, bag `BAG20260518152744831`, list branch `75`, hub branch `73`.

Generated by `docs/run_batch1_curls.sh`.

---

HDRDOC

run_block '1. hubscan' \
"curl --location --request POST '${BASE}?request=hubscan' \\
  --header 'Authorization: Bearer \$TOKEN' \\
  --header 'X-App-Version: 22.1.0' \\
  --header 'X-App-Platform: ios' \\
  --form 'docket_no=558751776258671' \\
  --form 'branch_id=73' \\
  --form 'user_id=1' \\
  --form 'status=Hub In'" \
  curl -sS -w $'\n__HTTP__:%{http_code}' --location --request POST "${BASE}?request=hubscan" \
  "${HDR[@]}" \
  --form 'docket_no=558751776258671' \
  --form 'branch_id=73' \
  --form 'user_id=1' \
  --form 'status=Hub In'

run_block '2. gethubscanlogs' \
"curl --location --request GET '${BASE}?request=gethubscanlogs&branch_id=73&limit=50' \\
  --header 'Authorization: Bearer \$TOKEN' \\
  --header 'X-App-Version: 22.1.0' \\
  --header 'X-App-Platform: ios'" \
  curl -sS -w $'\n__HTTP__:%{http_code}' --location --request GET "${BASE}?request=gethubscanlogs&branch_id=73&limit=50" \
  "${HDR[@]}"

run_block '3. getshipmentscanhistory' \
"curl --location --request GET '${BASE}?request=getshipmentscanhistory&docket_no=558751776258671' \\
  --header 'Authorization: Bearer \$TOKEN' \\
  --header 'X-App-Version: 22.1.0' \\
  --header 'X-App-Platform: ios'" \
  curl -sS -w $'\n__HTTP__:%{http_code}' --location --request GET "${BASE}?request=getshipmentscanhistory&docket_no=558751776258671" \
  "${HDR[@]}"

run_block '4. addshipmenttobag' \
"curl --location --request POST '${BASE}?request=addshipmenttobag' \\
  --header 'Authorization: Bearer \$TOKEN' \\
  --header 'X-App-Version: 22.1.0' \\
  --header 'X-App-Platform: ios' \\
  --form 'bag_code=BAG20260518152744831' \\
  --form 'docket_no=825411779084407' \\
  --form 'branch_id=1' \\
  --form 'user_id=1'" \
  curl -sS -w $'\n__HTTP__:%{http_code}' --location --request POST "${BASE}?request=addshipmenttobag" \
  "${HDR[@]}" \
  --form 'bag_code=BAG20260518152744831' \
  --form 'docket_no=825411779084407' \
  --form 'branch_id=1' \
  --form 'user_id=1'

run_block '5. getbagdetails' \
"curl --location --request GET '${BASE}?request=getbagdetails&bag_code=BAG20260518152744831' \\
  --header 'Authorization: Bearer \$TOKEN' \\
  --header 'X-App-Version: 22.1.0' \\
  --header 'X-App-Platform: ios'" \
  curl -sS -w $'\n__HTTP__:%{http_code}' --location --request GET "${BASE}?request=getbagdetails&bag_code=BAG20260518152744831" \
  "${HDR[@]}"

run_block '6. listbags' \
"curl --location --request GET '${BASE}?request=listbags&branch_id=75' \\
  --header 'Authorization: Bearer \$TOKEN' \\
  --header 'X-App-Version: 22.1.0' \\
  --header 'X-App-Platform: ios'" \
  curl -sS -w $'\n__HTTP__:%{http_code}' --location --request GET "${BASE}?request=listbags&branch_id=75" \
  "${HDR[@]}"

run_block '7. createbag (metal_seal_no required)' \
"curl --location --request POST '${BASE}?request=createbag' \\
  --header 'Authorization: Bearer \$TOKEN' \\
  --header 'X-App-Version: 22.1.0' \\
  --header 'X-App-Platform: ios' \\
  --form 'origin_branch_id=37' \\
  --form 'destination_branch_id=75' \\
  --form 'bag_code=BAG_TEST_PROBE' \\
  --form 'metal_seal_no=SEAL_TEST_PROBE' \\
  --form 'user_id=1'" \
  curl -sS -w $'\n__HTTP__:%{http_code}' --location --request POST "${BASE}?request=createbag" \
  "${HDR[@]}" \
  --form 'origin_branch_id=37' \
  --form 'destination_branch_id=75' \
  --form 'bag_code=BAG_TEST_PROBE' \
  --form 'metal_seal_no=SEAL_TEST_PROBE' \
  --form 'user_id=1'

echo "Wrote $OUT"
